### ISSUE TITLE
Installation Guide Update

### ISSUE THREAD

**Issue by ramzizelfani** [saleor/saleor-platform#121]
Update installation guide as well as saleor-platform repository to include the new react-storefront submodule and remove the deprecated saleor-storefront submodule as well as including a detailed process of updating a submodule to a specific tag/commit. Thank you

**Comment by slamer59** [comment]
Hello,
I think it is good to document better this point. 

I would even refactor this git repo because of submodule usage. 
Using submodule is not nowadays a considered a good practice and not used a lot. 

First I tought about a monorepo but this is not good either since every submodules are independant. 

Then I remember that docker-compose is able to build from git ([Since docker can](
https://docs.docker.com/engine/reference/commandline/build/#git-repositories)) ! 

It would clearer that this repo is just a magical glue made of the three submodules, people can replace one brick by another (mainly saleor-storefront IMHO). 

Finally, to have every git repo in parallel, everygood idea can create [kind of workspace](https://code.visualstudio.com/docs/editor/workspaces). 

Exemple:
```
    build:
      context: https://github.com/saleor/saleor.git#main
```

Working example where we can imagine a replacement of #main by an environment variable. 

```
version: "2"

services:
  api:
    ports:
      - 8000:8000
    build:
      context: https://github.com/saleor/saleor.git#main
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      - ./saleor/saleor/:/app/saleor:Z
      - ./saleor/templates/:/app/templates:Z
      - ./saleor/tests/:/app/tests
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=http://localhost:9000/

  storefront:
    build:
      context: https://github.com/saleor/saleor-storefront.git#main
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    command: npm start

  dashboard:
    build:
      context: https://github.com/saleor/saleor-dashboard.git#main
      dockerfile: ./Dockerfile.dev
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0

  db:
    image: library/postgres:11.1-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: https://github.com/saleor/saleor.git#main
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./saleor/saleor/:/app/saleor:Z,cached
      - ./saleor/templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge

```
