### ISSUE TITLE
Login went wrong. Please try again.

### ISSUE THREAD

**Issue by lacondeguy** [saleor/saleor-platform#280]
I have carefully read this issue: [#274](https://github.com/saleor/saleor-platform/issues/274) I also can't log in to the test account. 
1)   it's not working for me .. was erorr: "unknown command "db" for "docker compose down"
       `docker compose down --volumes db `

      including the VM IP address among environment IPs didn't work for me either
      
      ```
      services:
      api:
      environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,api,x.x.x.x
      ```
     
2)   also i have this issue:
      do i need to change localhost here to my vm ip?
      `- DASHBOARD_URL=http://localhost:9000/`

![url issue](https://i.ibb.co/s6pyYZB/2.png)
