### ISSUE TITLE
Login went wrong. Please try again.

### ISSUE THREAD

**Issue by thephilluk** [saleor/saleor-platform#298]
Hi there,

I checked both issues with the same name (#274 & #280) for solutions and tried those, but the issue still persists.

after following the guide for Docker installation [here](https://docs.saleor.io/docs/3.x/setup/docker-compose#installation) and everything started up without errors.

when trying to log in with my superuser I get the "Login went wrong. Please try again." error message.
After checking the Dev Console I can see that the Dashboard is trying to reach the GraphQL instance on my local machine but the Containers run on my local server.

I tried the methods listed in the Issues I mentioned:
 - adding the IP / Hostname of the Server in the docker-compose.yml under services, api, ALLOWED_HOSTS
 - adding the `API_URL=http://x.x.x.x:8000/graphql/` env variable under services, dashboard, both with Port and without.
 - running `docker compose down --volumes db` and running the migrations again.

unfortunately after that the issue still persists.
most recent try after all tried fixes: [Imgur Link](https://i.imgur.com/msh9TKS.png)

Ports 8000 & 9000 are allowed through the Firewall

any help is appreciated and if you need any info

current docker-compose:
```
version: "3.4"

services:
  api:
    image: ghcr.io/saleor/saleor:3.16.1
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://x.x.x.x:9000/
      - ALLOWED_HOSTS=localhost,api,x.x.x.x

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.16.1
    ports:
      - 9000:80
    restart: unless-stopped

  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - API_URL=http://x.x.x.x:8000/graphql/

  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.16.1
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
```

**Comment by shakeelasim86** [comment]
Hi every one, i am trying to follow https://github.com/saleor/saleor-platform for development purpose but when try to access my saleor dashboard it gives me error as under:-
Failed to load resource: net::ERR_CONNECTION_REFUSED                                                                     localhost:8000/graphql/:1 
please guide me how to setup .env exactly as i have configured my public-ip:8000 in .yml file but while accessing it points to localhost:8000.  Here is my yml file attached for better understanding. Due to unsuccessfull attempts i have duplicated env variables for every container/ service.  thanks for your cooperation

version: "3.4"

services:
  api:
    image: ghcr.io/saleor/saleor:unstable-main #ghcr.io/saleor/saleor:3.17
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
   env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://public-ip:9000/
      - ALLOWED_HOSTS=localhost,api,public-ip
      - API_URI=http://public-ip:8000/graphql/
  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
   ports:
      - 9000:80
    restart: unless-stopped
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://public-ip:9000/
      - ALLOWED_HOSTS=localhost,api,public-ip
      - API_URI=http://public-ip:8000/graphql/
  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - API_URI=http://public-ip:8000/graphql/
  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.17
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://public-ip:9000/
      - ALLOWED_HOSTS=localhost,api,public-ip
      - API_URI=http://public-ip:8000/graphql/
    depends_on:
      - redis
      - mailpit
    volumes:
     # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:

    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge

**Comment by brandoncazander** [comment]
I had this same issue and had to run this command to update the API_URL after bringing everything up with `docker compose up`:

```bash
docker exec -it -e API_URL=http://public-ip:8000/graphql/ <dashboard container ID> /docker-entrypoint.d/50-replace-api-url.sh
```

I got this from [the saleor-dashboard docker docs](https://github.com/saleor/saleor-dashboard/blob/698e2cd0c10ce8b71b4f5c5726fc68272dd1ad25/docs/docker.md?plain=1#L20C1-L20C95). It would be really nice if you could just override this as an environment variable at runtime but it appears impossible for now, at least from what I tried.

**Comment by yajuve** [comment]
You can also set your `API_URL` value in your `docker-compose.yml` as follow:
```yaml
  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    ports:
      - 9000:80
    restart: unless-stopped
    environment:
      - API_URL=<your-IP-here>:8000/graphql/ # <-- replace your-IP-here
```
